package AppUtility.mapping;

public enum MapProperty {
    SSN_SPLIT,
    SSN_DELIMITER,
    SSN_UNDECORATED,
    DATE_TYPE,
    DATE_SPLIT,
    DATE_SECTION,
    DATE_FORMAT,
    DATE_DELIMITER,
    GENDER_STYLE,
    SSN_SECTION,
    DATA_TYPE,
    CONDITIONAL,
    TEXT_VALUE,
    ALWAYS_CHECKED,
    PHONE_SPLIT,
    PHONE_SECTION,
    HAS_DEFAULT,
    DEFAULT_VALUE,
    IS_DEPENDENT_FIELD,
    DEPENDENT;
}
